### ISSUE TITLE
emit transaction failed: error_class=NoMethodError error="undefined method `+'

### ISSUE THREAD

**Issue by asafpelegcodes** [SumoLogic/fluentd-kubernetes-sumologic#126]
K8s Version (EKS) - 1.11
Using image - sumologic/fluentd-kubernetes-sumologic:v2.1.0
ENV variables changed...
sumologic.numThreads = 15
SOURCE_CATEGORY_PREFIX = ""
SOURCE_CATEGORY_REPLACE_DASH = "-"

I've got a super noisy app that's causing my fluentd daemon set to start spewing the following errors every few seconds..
```
emit transaction failed: error_class=NoMethodError error="undefined method `+' for nil:NilClass" location="/var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/output.rb:1255:in `submit_flush_once'"
```

```
2019-04-18 01:55:58 +0000 [warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `+' for nil:NilClass" location="/var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/output.rb:1255:in `submit_flush_once'" tag="containers.mnt.log.containers.THENOISYAPP.log"
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/output.rb:1255:in `submit_flush_once'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/output.rb:781:in `emit_buffered'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/output.rb:759:in `emit_events'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/out_copy.rb:58:in `block in process'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/out_copy.rb:56:in `each'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/out_copy.rb:56:in `each_with_index'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/out_copy.rb:56:in `process'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/multi_output.rb:148:in `emit_sync'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-forest-0.3.3/lib/fluent/plugin/out_forest.rb:173:in `emit'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/compat/output.rb:201:in `process'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/bare_output.rb:53:in `emit_sync'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/event_router.rb:159:in `emit_events'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/event_router.rb:96:in `emit_stream'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/out_relabel.rb:29:in `process'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/output.rb:768:in `emit_sync'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/event_router.rb:159:in `emit_events'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/event_router.rb:96:in `emit_stream'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/in_tail.rb:397:in `receive_lines'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/in_tail.rb:515:in `wrap_receive_lines'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/in_tail.rb:739:in `block in handle_notify'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/in_tail.rb:783:in `with_io'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/in_tail.rb:717:in `handle_notify'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/in_tail.rb:713:in `block in on_notify'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/in_tail.rb:713:in `synchronize'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/in_tail.rb:713:in `on_notify'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/in_tail.rb:545:in `on_notify'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin/in_tail.rb:631:in `on_timer'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-04-18 01:55:58 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by bin3377** [comment]
There is no sumologic related code in the stack trace. And it did refer to  https://github.com/tagomoris/fluent-plugin-forest
Are you using this plugin in the fluentd pipeline?

**Comment by asafpelegcodes** [comment]
Yes we are using it because it's needed for our log backups in s3 while using a feature that allows us to embed the tag into the s3 path

see link below
https://github.com/fluent/fluent-plugin-s3#v012-style

**Comment by asafpelegcodes** [comment]
@bin3377 does this mean I'm barking up the wrong tree? 

**pun intended**

**Comment by bin3377** [comment]
you should probably open issue on https://github.com/tagomoris/fluent-plugin-forest
So far I don't think it's related to our plugin
